### PR TITLE
Fix permission denied, mkdir '/home/runner' on a self-hosted runner

### LINKED ISSUE #13: `EACCES: permission denied, mkdir '/home/runner' occurred on a self-hosted runner
On a self-hosted runner, the following error occurred.

```
Run engineerd/setup-kind@v0.3.0
downloading kind from https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64
##[error]EACCES: permission denied, mkdir '/home/runner'
```

### PR DESCRIPTION
**Pull request by superbrothers**
Fixes #13

### CODE REVIEW

File: src/kind.ts [hunk 1]
```diff
@@ -70,15 +70,20 @@ export function getKindConfig(): KindConfig {
...
 export async function downloadKind(version: string) {
-    let url: string = `https://github.com/kubernetes-sigs/kind/releases/download/${version}/kind-linux-amd64`;
-    console.log("downloading kind from " + url);
-    let downloadPath: string | null = null;
-    downloadPath = await tc.downloadTool(url);
-    const binPath: string = "/home/runner/bin";
-    await io.mkdirP(binPath);
-    await exec.exec("chmod", ["+x", downloadPath]);
-    await io.mv(downloadPath, path.join(binPath, "kind"));
+    let toolPath: string = tc.find("kind", version);
```
Comment (radu-matei) [inline src/kind.ts]: Is this because the tool has already been downloaded on the runner?

Then I would much rather make the check outside of `downloadKind` - what do you think?

Comment (radu-matei) [reply src/kind.ts]: Actually, in this case, it might even make sense to expose this as a config for the action?

Comment (superbrothers) [reply src/kind.ts]: > Then I would much rather make the check outside of downloadKind - what do you think?

It is better. I'll change it that way.

Comment (superbrothers) [reply src/kind.ts]: Generally, downloaded tools in actions are cached and reused (e.g., actions/setup-go), so I feel that there is no need to expose it as a config. Is my understanding correct?

Comment (superbrothers) [reply src/kind.ts]: > Then I would much rather make the check outside of downloadKind - what do you think?

I did it at 76e5e91.
